header: "&2TerraTales&7RP\n&6Branch: &7Beta [2.5]"
footer: "&6Discord: &7discord.gg/aswQNetTtH\n&6Store: &7 https://store.terratalesrp.com\n&c&oStaff will never request any items in-game for issues unless it is in a ticket in Discord.\n&7&oDisclose any bugs you encounter for a reward on server release!"
