teleportenabled: true
teleportauto: false
godmode: false
muted: false
jailed: false
ip-address: 71.197.214.195
afk: false
socialspy: false
npc: false
powertoolsenabled: true
accepting-pay: true
baltop-exempt: false
timestamps:
  lastteleport: 0
  lastheal: 0
  mute: 0
  jail: 0
  onlinejail: 0
  logout: 1690322783915
  login: 1690322712278
money: '0'
last-account-name: Laika0xC1
logoutlocation:
  world: 6f4374b0-da68-4a3f-84ef-20fb3df70fa1
  world-name: world
  x: -29.59489542350627
  y: 69.0
  z: -82.21993829448506
  yaw: -99.59992980957031
  pitch: 32.24992370605469
